CREATE DATABASE MyDB
ON
PRIMARY
	(NAME = MyDB_Prm,
	FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\MyDB_Prm.mdf',
	SIZE = 4 MB,
	MAXSIZE =  UNLIMITED,
	FILEGROWTH = 8 MB),
FILEGROUP MyDB_FG1
	(NAME = MyDB_FG1_1,
	FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\MyDB_FG1_1.ndf',
	SIZE = 1 MB,
	MAXSIZE =  UNLIMITED,
	FILEGROWTH = 8 MB),
	(NAME = MyDB_FG1_2,
	FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\MyDB_FG1_2.ndf',
	SIZE = 1 MB,
	MAXSIZE =  UNLIMITED,
	FILEGROWTH = 8 MB)
LOG ON
	(NAME = MyDB,
	FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\MyDB.ldf',
	SIZE = 1 MB,
	MAXSIZE =  UNLIMITED,
	FILEGROWTH = 8 MB)